server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-service-db
    username: postgres
    password: longthanh04
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: SH9xiK7S2IdaopOjIdoMPILj0GpRIvkDXminzOh72xQ+opwyXReQkn9eWd7kEH7m
  expiration: 86400000
